bindAddr = "frps.lemondemon.sbs"
bindPort = 7000

vhostHTTPPort = 82
vhostHTTPSPort = 445

transport.maxPoolCount = 2000
transport.tcpMux = true
transport.tcpMuxKeepaliveInterval = 60
transport.tcpKeepalive = 7200
transport.tls.force = true

webServer.addr = "83.229.121.144"
webServer.port = 7500
webServer.user = "demon"
webServer.password = "xdzyj159357"
webServer.pprofEnable = false

log.to = "./frps.log"
log.level = "info"
log.maxDays = 3
log.disablePrintColor = false

auth.method = "token"
auth.token = "HQUYfIEg7IZbhlXg"

allowPorts = [
  { start = 5000, end = 50000 }
]

maxPortsPerClient = 20
udpPacketSize = 1500
natholeAnalysisDataReserveHours = 168

